### ISSUE TITLE
Pointing simulation show wrong completion rate

### ISSUE THREAD

**Issue by takagi-naoj** [monodera/pfs_target_uploader#138] opened 2023-11-22 20:55 UTC
**Describe the bug**
When a target list only contains medium-resolution is uploaded, the calculated completion rate for medium-resolution becomes "nan", while that for low-resolution is not zero. 

**Expected behavior**
The completion rate for medium-resolution should be calculated properly, while that for low-resolution should be zero, nan, or something else that shows no low-resolution observations is in the target list.

**Screenshots**
![スクリーンショット 2023-11-22 10 33 40](https://github.com/monodera/pfs_target_uploader/assets/95534602/28c86e2c-da42-4f9d-93e1-c2db19475950)

**Computer Environment:**
 - OS: macOS 12.7.1
 - Browser: Chrome 119.0.6045.159

**Comment by monodera** [comment] 2023-11-28 00:59
duplicate of #124 and will be fixed by #128

**Closed by monodera** 2023-11-28 00:59 UTC
Labels: bug, duplicate
